# Generated by Django 5.1.4 on 2025-02-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_author_brief_description_alter_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
    ]
