# Generated by Django 5.1.4 on 2025-02-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='topic',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
