# Generated by Django 5.1.4 on 2025-02-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_postmodel_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='topic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
