# Generated by Django 5.1.4 on 2025-02-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_postmodel_comment_alter_postmodel_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='comment',
            new_name='comment_On_The_Post',
        ),
    ]
