# Generated by Django 5.1.4 on 2025-02-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_rename_comment_postmodel_comment_on_the_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='comment_On_The_Post',
            new_name='comment_on_the_post',
        ),
    ]
