# Generated by Django 5.1.4 on 2025-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_rename_comment_on_the_post_postmodel_comment_on_the_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='subject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='your_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='your_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
