# Generated by Django 5.1.4 on 2025-03-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_comment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
